import React from 'react';
import { Container, Stack } from '../shared/layout';
import { Card } from '../shared/ui';

export default function TermsPage() {
  return (
    <Container maxWidth="md">
      <Stack gap={6}>
        <div>
          <h1 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>Terms of Service</h1>
          <p style={{ color: 'var(--color-text-secondary)' }}>Last updated: {new Date().toLocaleDateString()}</p>
        </div>
        
        <Card padding="lg">
          <Stack gap={4}>
            <section>
              <h2>Acceptable Use</h2>
              <p>Epigrapher AI is provided for educational, research, and scholarly purposes. You agree not to use the service for any illegal or unauthorized purpose.</p>
            </section>
            
            <section>
              <h2>AI Limitations</h2>
              <p>Our platform uses experimental artificial intelligence for epigraphic analysis. Translations and transliterations are generated by AI and may contain inaccuracies. Users are strongly encouraged to independently verify all results for academic or professional publication.</p>
            </section>

            <section>
              <h2>Intellectual Property</h2>
              <p>You retain all rights to the images and text you upload. Epigrapher AI claims no ownership over user-uploaded content.</p>
            </section>
          </Stack>
        </Card>
      </Stack>
    </Container>
  );
}
